version: '3.8'

services:
  # MySQL Database Service
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db_pands
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: price_checker_service
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_network

  # Redis Service
  redis:
    image: redis:6.0
    container_name: redis_pands
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  # Laravel App Service
  app:
    container_name: panda_php_app
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network
    depends_on:
      - mysql_db
      - redis

  scheduler:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./scheduler/cronjobs:/etc/cron.d/cronjobs
    entrypoint: ["sh", "-c", "while true; do php /var/www/price_checker_service/artisan schedule:run; sleep 60; done"]
    networks:
      - laravel_network
    depends_on:
      - mysql_db
      - redis
  queue_worker:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel_queue_worker
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    entrypoint: ["sh", "-c", "php /var/www/price_checker_service/artisan queue:work --sleep=3 --tries=3"]
    networks:
      - laravel_network
    depends_on:
      - mysql_db
      - redis   
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_panda
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:

volumes:
  mysql_data: